ToDo/djangoProject1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('todo.urls')),
    path('admin/', admin.site.urls),
]

ToDo/todo/urls.py
from django.urls import path

from . import views

app_name = 'todo'
urlpatterns = [
    path('', views.home, name='index'),
    path('todo/', views.todo_index, name='todoList'),
    path('todo/<id>/delete', views.todo_delete, name='delete'),
    path('todo/<id>/edit', views.todo_edit, name='edit'),
    path('todo/create', views.todo_create, name='create')
]

ToDo/todo/models.py
from django.db import models
from django.forms import ModelForm


# Create your models here.
class ListEntry(models.Model):
    Id = models.AutoField(primary_key=True)
    Description = models.CharField(max_length=200)
    isDone = models.BooleanField()
    class Meta:
        db_table: "listentry"

ToDo/todo/forms.py
from django import forms
from django.forms import ModelForm
from todo.models import ListEntry


class CreateForm(forms.ModelForm):
    # specify the name of model to use
    class Meta:
        model = ListEntry
        exclude = ['Id', 'isDone']


class EditForm(forms.ModelForm):
    # specify the name of model to use
    class Meta:
        model = ListEntry
        exclude = ['Id']

ToDo/todo/views.py
from django.shortcuts import (get_object_or_404,
                              render,
                              HttpResponseRedirect)

# Create your views here.
from django.http import HttpResponse
from .models import ListEntry
from .forms import EditForm, CreateForm
def home(request):
    context = {}
    return render(request, 'todo/home.html', context)

def todo_index(request):
    if request.method =="POST":
        createForm = CreateForm(request.POST)
        if createForm.is_valid():
            obj = ListEntry()
            obj.Description = createForm['Description'].value()
            obj.isDone = 0
            obj.save()
        return HttpResponseRedirect("/todo")
    else:
        createForm = CreateForm()
    todo_list = ListEntry.objects.order_by('Id')
    context = {
        'todo_list': todo_list,
        'createForm': createForm
    }
    return render(request, 'todo/index.html', context)

def todo_delete(request, id):
    obj = get_object_or_404(ListEntry, pk=id)
    context = {'obj': obj}
    if request.method =="POST":
        obj.delete()
        return HttpResponseRedirect("/todo")
    return render(request, "todo/delete.html", context)

def todo_create(request):
    context = {}
    if request.method =="POST":
        createForm = CreateForm(request.POST)
        if createForm.is_valid():
            obj = ListEntry()
            obj.Description = createForm['Description'].value()
            obj.isDone = 0
            obj.save()
        return HttpResponseRedirect("/todo")
    else:
        createForm = CreateForm()
    return render(request, "todo/create.html", {"form": createForm})

def todo_edit(request, id):
    obj = get_object_or_404(ListEntry, pk=id)

    if request.method =="POST":
        form = EditForm(request.POST)
        if form.is_valid():
            obj.Description = form['Description'].value()
            obj.isDone = form['isDone'].value()
            obj.save()
        return HttpResponseRedirect("/todo")
    else:
        form = EditForm(instance=obj)
        context = {'obj': obj,
                   "form": form}
    return render(request, "todo/edit.html", context)

ToDo/templates/todo/create.html
{% load static %}

<link rel="stylesheet" href="{% static 'todo/bootstrap/dist/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'todo/style.css' %}">
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <hr/>
    <div>
        <form method="POST" action="{% url 'todo:create' %}" id="Create-Form">
                    <!-- Security token by Django -->
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Add" class="btn btn-primary" >
        </form>
    </div>
</body>
</html>

ToDo/templates/todo/delete.html
{% load static %}

<link rel="stylesheet" href="{% static 'todo/bootstrap/dist/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'todo/style.css' %}">

<div class="modal fade" id="ListEntryDeleteModal" tabindex="-1" role="dialog">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header p-4">
				<a href="#" onclick="CloseModal()">&#215</a>
				<h5>Delete ListEntry</h5>
            </div>
            <div class="p-4">
    <!-- Create a Form -->
                <form method="POST" action="{% url 'todo:delete' obj.Id %}">
                    <!-- Security token by Django -->
                    {% csrf_token %}
                    Are you want to delete this item ?
                    <input type="submit" value="Yes" />
                </form>
            </div>
        </div>
    </div>
</div>

<script>
	CloseModal = function () {
		$('#ListEntryDeleteModal').modal('hide');
	}
</script>

ToDo/templates/todo/edit.html
{% load static %}

<link rel="stylesheet" href="{% static 'todo/bootstrap/dist/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'todo/style.css' %}">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="modal fade" id="ListEntryEditModal" tabindex="-1" role="dialog">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header p-4">
				<a href="#" onclick="CloseModal()">&#215</a>
				<h5>Edit ListEntry</h5>

			</div>
            <div class="p-4">
                <!-- Create a Form -->
                <form method="POST" action="{% url 'todo:edit' obj.Id %}">
                    <!-- Security token by Django -->
                    {% csrf_token %}
                {{ form }}
                <input type="submit" value="Submit" >
                </form>
            </div>
        </div>
    </div>
</div>
</div>
</body>
</html>
<script>
	CloseModal = function () {
		$('#ListEntryEditModal').modal('hide');
	}
</script>

ToDo/templates/todo/footer.html
{% load static %}

<link rel="stylesheet" href="{% static 'todo/bootstrap/dist/css/bootstrap.min.css' %}">

<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ToDo - Django
        </div>
</footer>

ToDo/templates/todo/header.html
{% load static %}

<link rel="stylesheet" href="{% static 'todo/bootstrap/dist/css/bootstrap.min.css' %}">

<header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">ToDo-App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
	                    <li class="nav-item">
		                    <a class="nav-link text-dark" href="/">Home</a>
	                    </li>
	                    <li class="nav-item">
		                    <a class="nav-link text-dark" href="/todo/">ToDoList</a>
	                    </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>

ToDo/templates/todo/home.html
{% load static %}

<link rel="stylesheet" href="{% static 'todo/bootstrap/dist/css/bootstrap.min.css' %}">
{% include "todo/header.html" %}
<div class="container">
    <main role="main" class="pb-3">
        <div class="text-center">
            <h1 class="display-4">Welcome</h1>
            <p>This is a simple Web-Application done with the help of the Web-Framework Django.</p>
            <p>The Web-Application is a simple todo List, new List entries can be created, existing ones can be edited and Entries can be deleted</p>
        </div>
    </main>
</div>
{% include "todo/footer.html" %}

ToDo/templates/todo/index.html
{% load static %}
<script src="{% static "todo/jquery/dist/jquery.js" %}"></script>
<script src="{% static "todo/bootstrap/dist/js/bootstrap.js" %}"></script>
<link rel="stylesheet" href="{% static 'todo/bootstrap/dist/css/bootstrap.min.css' %}">

{% include "todo/header.html" %}
<div class="container">
    <main role="main" class="pb-3">
        <h1>To Do List</h1>
        <div id="create">
            <form method="POST" action="{% url 'todo:create' %}" id="Create-Form">
                <!-- Security token by Django -->
            {% csrf_token %}
            {{createForm}}
            <input type="submit" value="Add" class="btn btn-primary" >
            </form>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>isDone</th>
                    <th>Description</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            {% for entry in todo_list %}
                <tr>
                    <td>
                        {{ entry.isDone }}
                    </td>
                    <td>
                        {{ entry.Description }}
        {#				<a href="/todo/{{ entry.id }}/">{{ entry.Description }}</a>#}
                    </td>
                    <td>
                        <a href="#" onclick="LoadEditModal({{ entry.Id }})">Edit</a> |
                        <a href="#" onclick="LoadDeleteModal({{ entry.Id }})">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </main>
</div>
<div id="modalContainer"></div>
{% include "todo/footer.html" %}
<script type="text/javascript">
	    LoadDeleteModal = function (ListEntryId) {
        $("#modalContainer").load(`/todo/${ListEntryId}/delete`, function() {
			$('#ListEntryDeleteModal').modal( 'show');

        });
    };
	LoadEditModal = function (ListEntryId) {
		$("#modalContainer").load(`/todo/${ListEntryId}/edit`, function () {
			$('#ListEntryEditModal').modal('show');
        });
    };
</script>